## AWS Region ##
region: us-west-2

## Basic Parameters for EKS Cluster and Worker Nodes
instance_count: 1
# sshKey: rancher-dev
security_grp: sg-0f63af43391e2d781
instance_type: t3a.medium

## Private subnets group 1 ##
subnet_grp_1a: subnet-0ee270de6a08b94c2
subnet_grp_1b: subnet-006816ece808f4cdc
subnet_grp_1c: subnet-04fad85206c9bed9e

## Tags ##
worker_name: eks-chart-worker
name: eks-chart-dev-1
displayName: eks-chart1
ngName: eks-chart-dev-ng-1
app_name: eks-chart-dev-test
ci: 1906ca5297cacd14a90cde24a253af16
creator: rancher-admin-user
env: dev
function: app
risk: s
uai: deprecated

## EKS Kubernetes Version ###
kubeversion: 1.21

