variables:
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
  - rancher-runner
  script:
    - echo "Rancher EKS Provisioning"
    - sudo su -
    - pwd
    # - ./rancher login https://rancher-dev.corp.wabtec.com --token ${token}
    # - ./rancher clusters kf local > /root/local-kubeconfig
    # - export KUBECONFIG=/root/local-kubeconfig
    - kubectl get eksclusterconfig -n ent-tools-team
    - cd $CI_PROJECT_DIR
    - helm list -n ent-tools-team
  only:
  - master

dry-run:
  stage: test
  tags:
  - rancher-runner
  script:
    - echo "Rancher EKS Provisioining"
    - sudo su - 
    - kubectl get eksclusterconfig -n ent-tools-team
    - cd $CI_PROJECT_DIR
    - helm list -n ent-tools-team
    - helm install -f ./eksTemplate/values.yaml ent-tools-sanbox-dev-2 ./eksTemplate -n ent-tools-team --dry-run
  only:
  - master

rancher-eks-release:
  stage: deploy
  when: manual
  tags:
  - rancher-runner
  script:
    - echo "Rancher EKS Deployment"
    - sudo su -
    - ./rancher login https://rancher-dev.corp.wabtec.com --token ${token}
    - ./rancher clusters kf local > /root/local-kubeconfig
    - export KUBECONFIG=/root/local-kubeconfig
    - kubectl get eksclusterconfig -n ent-tools-team
    - cd $CI_PROJECT_DIR
    - helm list -n ent-tools-team
    - helm install -f ../eksTemplate/values.yaml ent-tools-sanbox-dev-2 ../eksTemplate -n ent-tools-team
  only:
  - master
