variables:
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
  - rancher-runner
  script:
    - echo "Rancher EKS Provisioning"
    - sudo su -
    - cd /root/rancher-v2.6.4
    - ./rancher login https://rancher-dev.corp.wabtec.com --token ${token}
    - ./rancher clusters kf local > /root/local-kubeconfig
    - export KUBECONFIG=/root/local-kubeconfig
    - kubectl get eksclusterconfig -n ent-tools-team
    - helm list -n ent-tools-team
    - cd $CI_PROJECT_DIR
    - pwd
    - helm install -f ./eksTemplate/values.yaml ent-tools-sanbox-dev-3 ./eksTemplate

  only:
  - master

dry-run:
  stage: test
  when: manual
  tags:
  - rancher-runner
  script:
    - echo "Rancher EKS Provisioining"
    - sudo su - 
    - ./root/rancher-v2.6.4/rancher login https://rancher-dev.corp.wabtec.com --token ${token}
    - ./rancher clusters kf local > /root/local-kubeconfig
    - kubectl get eksclusterconfig -n ent-tools-team
    - helm list 
    - helm install -f ../eksTemplate/values.yaml ent-tools-sanbox-dev-3 ../eksTemplate
  only:
  - master

rancher-eks-release:
  stage: deploy
  when: manual
  tags:
  - rancher-runner
  script:
    - echo "Rancher EKS Deployment"
    - sudo su -
    - cd /root/rancher-v2.6.4
    - ./rancher login https://rancher-dev.corp.wabtec.com --token ${token}
    - ./rancher clusters kf local > /root/local-kubeconfig
    - export KUBECONFIG=/root/local-kubeconfig
    - kubectl get eksclusterconfig -n ent-tools-team
    - helm list -n ent-tools-team
    - pwd
    - helm install -f ../eksTemplate/values.yaml ent-tools-sanbox-dev-3 ../eksTemplate
  only:
  - master
