apiVersion: eks.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: {{ .Values.name }}
  namespace: cattle-global-data
spec:
  amazonCredentialSecret: cattle-global-data:cc-px5ft
  displayName: {{ .Values.displayName }}
  imported: false
  kmsKey: ""
  kubernetesVersion: "1.21"
  loggingTypes:
  - api
  - audit
  - authenticator
  - controllerManager
  - scheduler
  nodeGroups:
  - desiredSize: ${instance-count}
    diskSize: 30
    ec2SshKey: ${rancherDev}
    gpu: false
    imageId: null
    instanceType: ${instance.type}
    labels: {}
    launchTemplate: null
    maxSize: 3
    minSize: 1
    nodegroupName: {{ .Values.ngName }}
    requestSpotInstances: false
    resourceTags: {}
    spotInstanceTypes: null
    subnets:
    - ${subnet-grp-1a}
    - ${subnet-grp-1b}
    - ${subnet-grp-1c}
    tags: {}
    userData: null
    version: "1.21"
  privateAccess: true
  publicAccess: false
  publicAccessSources:
  - 0.0.0.0/0
  region: ${region}
  secretsEncryption: false
  securityGroups:
  - ${security-grp}
  serviceRole: ""
  subnets:
  - ${subnet-grp-1a}
  - ${subnet-grp-1b}
  - ${subnet-grp-1c}
  tags: 
    app: ${app-name}
    ci: ${ci}
    creator: ${creator}
    env: ${env}
    function: ${function}
    risk: ${risk}
    uai: ${uai}
