apiVersion: eks.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: {{ .Values.name }}
  namespace: cattle-global-data
spec:
  amazonCredentialSecret: cattle-global-data:cc-px5ft
  displayName: {{ .Values.displayName }}
  imported: false
  kmsKey: ""
  kubernetesVersion: {{ .Values.eks_version}}
  loggingTypes:
  - api
  - audit
  - authenticator
  - controllerManager
  - scheduler
  nodeGroups:
  - desiredSize: {{ .Values.instance_count }}
    diskSize: 30
    ec2SshKey: {{ .Values.sshKey }}
    gpu: false
    imageId: null
    instanceType: {{ .Values.instance_type }}
    labels: {}
    launchTemplate: null
    maxSize: 3
    minSize: 1
    nodegroupName: {{ .Values.ngName }}
    requestSpotInstances: false
    resourceTags: {}
    spotInstanceTypes: null
    subnets:
    - {{ .Values.subnet_grp_1a }}
    - {{ .Values.subnet_grp_1b }}
    - {{ .Values.subnet_grp_1c }}
    tags: {}
    userData: null
    version: {{ .Values.eks_version}}
  privateAccess: true
  publicAccess: false
  publicAccessSources:
  - 0.0.0.0/0
  region: {{ .Values.region }}
  secretsEncryption: false
  securityGroups:
  - {{ .Values.security_grp }}
  serviceRole: ""
  subnets:
  - {{ .Values.subnet_grp_1a }}
  - {{ .Values.subnet_grp_1b }}
  - {{ .Values.subnet_grp_1c }}
  tags: 
    app: {{ .Values.app_name }}
    ci: {{ .Values.ci }}
    creator: {{ .Values.creator }}
    env: {{ .Values.env }}
    function: {{ .Values.function }}
    risk: {{ .Values.risk }}
    uai: {{ .Values.uai }}
